import type { Metadata } from "next";
import { Roboto_Flex } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSidebar";

const roboto_flex = Roboto_Flex({
  variable: "--font-roboto_flex",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto_flex.variable} `}>
        <SidebarProvider>
          <AppSidebar />
          <main className="w-full relative">
            <SidebarTrigger className="absolute" />
            <div className="lg:h-screen lg:min-h-screen lg:overflow-hidden">
              {children}
            </div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
